### ISSUE TITLE
Suggestions: Please Consider Never Writing C++ Code Specific to Particular Compiler Here.

### ISSUE THREAD

**Issue by ufolyah** [SIST-Manual/SIST_Manual#2]
Like `#include<bits/stdc++.h>`. This is only work for gnu c/c++ compiler. 
If someone use Clang on XCode or MSVC on windows, this will be a compile error, and students may found it hard and cost a lot of meaningless time to solve.
Only a suggestion, feed-backs are always welcome.

**Comment by DataCorrupted** [comment]
@Q71998 I wanted to ask about `stdc++.h ` too. The argument he proposed is reasonable. Please consider change it.
