### ISSUE TITLE
Notification: Reconsider Recommended Ubuntu Version. 

### ISSUE THREAD

**Issue by xudufy** [SIST-Manual/SIST_Manual#3]
In SI100 course of my year, the Ubuntu version is finally determined by the ROS version specified in course manual for robotic parts (Jade vs Indigo, 16.04 vs 14.04).

Reinstalling Ubuntu after trying hard but still cannot able to install different version of ROS is really a painful memory for me. I don't want it to happen again.

**Comment by makeecat** [comment]
Please use 16.04 LTS. You will need that for ROS.

**Comment by DataCorrupted** [comment]
We are using Ubuntu 1604 + Ros Kinetic now.  :)
Jade and Indigo have become history.

**Comment by xudufy** [comment]
[ROS Melodic Morenia LTS](http://wiki.ros.org/melodic/Installation) is out for Bionic. If they take robotics courses next year, shouldn't we move to that version at that time?

**Comment by DataCorrupted** [comment]
I am not aware that Melodic has published. Last time I checked it is still testing? In that case, I believe Soren will request for Melodic.

Nevertheless, Ubuntu 16.04 should work fine. I will later update the manual to specify that it's better to use ROS Melodic.
